### ISSUE TITLE
Unable to resolve "react-native-paper/src/components/BottomNavigation" from "node_modules/react-navigation-material-bottom-tabs/dist/navigators/createMaterialBottomTabNavigator.js"

### ISSUE THREAD

**Issue by dancomanlive** [react-navigation/react-navigation-material-bottom-tabs#23]
"react-navigation-material-bottom-tabs": "^0.4.0",
"react-navigation": "^2.17.0"
"react": "^16.5.2",
"react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz"

**Comment by brentvatne** [comment]
oh yeah, my bad. I thought that was a dependency of this lib for some reason but it looks like it's just a peer dependency

**Comment by brentvatne** [comment]
@dancomanlive - as per readme you should install react-native-paper as well: https://github.com/react-navigation/react-navigation-material-bottom-tabs#installation
