### ISSUE TITLE
How can I hide the tabbar in some screen

### ISSUE THREAD

**Issue by youngjuning** [react-navigation/react-navigation-material-bottom-tabs#7]
```js
// 指定页面隐藏header
const Stacks = [HomeStack, AntDMobileRNStack, PluginsStack]
Stacks.forEach((item) => {
  item.navigationOptions = ({ navigation }) => {
    let tabBarVisible = true
    if (navigation.state.index > 0) {
      tabBarVisible = false
    }
    return {
      tabBarVisible,
    }
  }
})
```

It's not work

**Comment by SrujithPoondla** [comment]
Were you able to figure out any solution? I am also looking for the same feature, tabBarVisible is not available in material bottom tab navigation. It is only available for bottomTabNavigator.

**Comment by juan-carlos-correa** [comment]
Same issue here, some info about solution?

**Comment by satya164** [comment]
Pull request welcome to add a `tabBarVisible` option. It needs to add a `display: none` style when `tabBarVisible` is `false`.

**Comment by satya164** [comment]
added in https://github.com/react-navigation/react-navigation-material-bottom-tabs/commit/f9d62a241e668653eccdb21c805050a645e3ef41

**Comment by youngjuning** [comment]
how can i use it.Which react-navigation version contain it tabBarVisible

**Comment by youngjuning** [comment]
Thanks Bro

**Comment by alikazemkhanloo** [comment]
I faced this issue, But I want to hide  tabbar when a I reach a screen deep in the stackNavigator.
my routes are something like this:
```
materialTabNavigator:{
    Homestack:{
         Homescreen, 
         Detailscreen
    },
    Librarystack: {        
          Libraryscreen,
          Detailscreen
     }
}
```
and I want to hide the tabbar when I reach the Detailscreen.
when I use `tabBarVisible` in `Homestack` it works fine, But using it in `Detailscreen`, doesn't.

I'm using react navigation.
